description: A JSON object with a key of `db`.

headers:
  ratelimit-limit:
    $ref: '../../../shared/headers.yml#/ratelimit-limit'
  ratelimit-remaining:
    $ref: '../../../shared/headers.yml#/ratelimit-remaining'
  ratelimit-reset:
    $ref: '../../../shared/headers.yml#/ratelimit-reset'

content:
  application/json:
    schema:
      type: object
      properties:
        db:
          $ref: '../models/database.yml'
      required:
        - db
    example:
      db:
        name: alpha
